// <auto-generated />
using HelpCenterSearch.Data;
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpCenterSearch.Migrations;

[DbContext(typeof(HelpCenterDbContext))]
[Migration("20260917072731_Initial")]
partial class _20260917072731_Initial
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("HelpCenterSearch.Models.Article", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("int");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<SqlVector<float>>("Embedding")
                    .HasColumnType("vector(1536)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Topic")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)");

                b.HasKey("Id");

                b.HasIndex("Title", "Content")
                    .HasAnnotation("SqlServer:FullTextCatalog", "ftCatalog")
                    .HasAnnotation("SqlServer:FullTextIndex", "PK_Articles");

                b.ToTable("Articles");
            });
#pragma warning restore 612, 618
    }
}
